# Generated by Django 5.2.16 on 2026-07-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pustak', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_descrption',
            new_name='book_description',
        ),
    ]
