# Generated by Django 5.2.16 on 2026-07-31 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pustak', '0002_rename_book_descrption_book_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_image',
            new_name='book_images',
        ),
    ]
