# Generated by Django 5.2.16 on 2026-07-31 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pustak', '0003_rename_book_image_book_book_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_images',
            new_name='book_image',
        ),
    ]
